apiVersion: v1

# What's the point of kind? Perhaps a collection of default settings?
kind: ProblemEbook

metadata:
  name: problem-book-example

data:
  # Could also be embeded
  data-source: LocalFilesystem

  directory: '.'

  preprocess:
    # Also could be here
    # convert-gib-to-sgf
    convert-ids: SimpleSanitize

book:
  auto-generate-positions: FromSortedIDs

  spec:
    position-type: Problem
    auto-rotate-crop-prefs:
      corner: BottomLeft
      prefer-flips: true

  diagram:
    type: SVG
    clear-marks: true

  template:
    chapter-size: 25
